[package]
name = "stub"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.14"
mockall_double = "0.1.0"
md-5 = { version = "0.10.1", default-features = false }
[target.'cfg(target_arch = "riscv32")'.dependencies]
esp32c3-hal = { package = "esp32c3-hal", git = "https://github.com/esp-rs/esp-hal", rev = "34b1e09" }
esp-hal-common = { package = "esp-hal-common", git = "https://github.com/esp-rs/esp-hal", rev = "34b1e09" }
riscv-rt = "0.8.1"
nb = "1.0.0"
riscv = "0.8.0"

[dev-dependencies]
assert2 = "0.3.6"
matches = "0.1.9"
mockall = "0.11.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"