[package]
name = "stub"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.16"
md-5 = { version = "0.10.5", default-features = false }

[target.'cfg(target_arch = "riscv32")'.dependencies]
esp32c3-hal = "0.2.0"
riscv = "0.8.0"
riscv-rt = "0.9.0"

[dev-dependencies]
assert2 = "0.3.6"
matches = "0.1.9"
mockall = "0.11.2"
mockall_double = "0.3.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
